version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    main: ./bin/slash
    binary: slash
    goos:
      - linux
      - darwin

archives:
  - formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

checksum:
  name_template: "checksums.txt"

release:
  make_latest: true
  mode: replace
  skip_upload: false
