name: Proto linter

permissions:
  contents: read

on:
  push:
    branches:
      - main
      - "release/v*.*.*"
  pull_request:
    branches:
      - main
      - "release/*.*.*"
    paths:
      - "proto/**"

jobs:
  lint-protos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0
      - name: Setup buf
        uses: bufbuild/buf-setup-action@v1.49.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: buf mod update
        run: buf mod update
        working-directory: proto
      - name: buf lint
        uses: bufbuild/buf-lint-action@06f9dd823d873146471cfaaf108a993fe00e5325 # v1.1.1
        with:
          input: "proto"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: buf format
        run: |
          if [[ $(buf format -d) ]]; then
            echo "Run 'buf format -w'"
            exit 1
          fi
